### PR TITLE
Move themes to seperate files

### PR DESCRIPTION
**Pull request by Akianonymus**
Let's save some seconds

### CODE REVIEW

**Comment by Akianonymus** [comment]
https://github.com/siduck76/NvChad/pull/226 should be merged after this pr

Benchmark: https://github.com/siduck76/NvChad/pull/226#issue-707237028

**Comment by Asocia** [comment]
After this merge commit, I'm having the following error: 
```
Error detected while processing /home/sahin/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/sahin/.config/nvim/init.lua:22: attempt to index field 'themes
' (a function value)
Press ENTER or type command to continue
```
The related line in my `init.lua` is this:
```
local base16 = require "base16"
base16(base16.themes["onedark"], true)
```
I don't know anything about lua. What should I change in order to make this work again?

**Comment by siduck76** [comment]
@Asocia 

local base16 = require 'base16'
base16(base16.themes("onedark"), true)

**Comment by siduck76** [comment]
also I suggest using old config!

**Pull request merged**
